// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJJ6OhyFul-zZvJYJgsHjAK9Dgs3A54WM',
    appId: '1:685305154027:web:322119291842d490cef1ae',
    messagingSenderId: '685305154027',
    projectId: 'sidumita-98802',
    authDomain: 'sidumita-98802.firebaseapp.com',
    storageBucket: 'sidumita-98802.appspot.com',
    measurementId: 'G-6S7Z4K5ZJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA26T801B4YQfpuTL0zxOJFjKoltZQDmjA',
    appId: '1:685305154027:android:eb16c63139d3cabdcef1ae',
    messagingSenderId: '685305154027',
    projectId: 'sidumita-98802',
    storageBucket: 'sidumita-98802.appspot.com',
  );
}
